import type { PromptItem } from "./types";

// Fonte: Guia AI First EMR: Seção 11, Biblioteca de prompts + prompts iniciais da Matriz.

export const promptCategories = [
  "Escrita",
  "Apresentações",
  "Reuniões",
  "Projetos",
  "Dados",
  "Aprendizagem",
  "Feedback",
  "Comunicação",
  "Criatividade",
  "Planejamento",
] as const;

export const prompts: PromptItem[] = [
  {
    id: "pr-primeira-versao",
    title: "Primeira versão de um texto",
    category: "Escrita",
    area: "todas",
    description: "Um ponto de partida com estrutura, clareza e tom definidos por você.",
    whenToUse: "Quando você precisa escrever algo e não quer começar da página em branco.",
    text: "Escreva uma primeira versão de [tipo de texto] sobre [tema], para [público], em tom [formal/informal/inspirador].",
    variables: ["tipo de texto", "tema", "público", "tom"],
    relatedSituations: ["sit-escrever"],
    tags: ["e-mail", "texto", "rascunho"],
    status: "publicado",
  },
  {
    id: "pr-reescrever",
    title: "Reescrever com outro tom",
    category: "Escrita",
    area: "todas",
    description: "Mantém as informações principais e ajusta clareza, tamanho ou formalidade.",
    whenToUse: "Quando o conteúdo está certo, mas a forma ainda não está.",
    text: "Reescreva este texto de forma mais [clara/breve/formal], mantendo as informações principais: [colar texto].",
    variables: ["estilo", "texto"],
    relatedSituations: ["sit-escrever", "sit-revisar"],
    tags: ["reescrever", "tom", "clareza"],
    status: "publicado",
  },
  {
    id: "pr-revisar",
    title: "Revisão crítica de uma entrega",
    category: "Escrita",
    area: "todas",
    description: "Identifica erros, ambiguidades e repetições antes de você entregar.",
    whenToUse: "Antes de enviar algo importante, e sempre com decisão final sua.",
    text: "Revise este conteúdo e identifique erros, ambiguidades, repetições e pontos que precisam de mais clareza: [texto].",
    variables: ["texto"],
    relatedSituations: ["sit-revisar"],
    tags: ["revisão", "qualidade"],
    status: "publicado",
  },
  {
    id: "pr-slides",
    title: "Estrutura de apresentação",
    category: "Apresentações",
    area: "todas",
    description: "Roteiro de slides a partir do seu objetivo e do seu público.",
    whenToUse: "Quando você tem o conteúdo, mas ainda não tem a narrativa.",
    text: "Sugira uma estrutura de apresentação sobre [tema], para [público], com duração de [tempo] e objetivo de [objetivo].",
    variables: ["tema", "público", "tempo", "objetivo"],
    relatedSituations: ["sit-apresentacao"],
    tags: ["slides", "narrativa", "deck"],
    status: "publicado",
  },
  {
    id: "pr-pauta",
    title: "Pauta de reunião com decisões esperadas",
    category: "Reuniões",
    area: "todas",
    description: "Objetivo, perguntas-chave, tempo por tema e decisões esperadas.",
    whenToUse: "Antes de marcar ou conduzir qualquer reunião relevante.",
    text: "Crie uma pauta para uma reunião sobre [tema], com objetivo de [objetivo], duração de [tempo] e decisões esperadas.",
    variables: ["tema", "objetivo", "tempo"],
    relatedSituations: ["sit-reuniao"],
    tags: ["reunião", "pauta"],
    status: "publicado",
  },
  {
    id: "pr-ata",
    title: "Ata com decisões e próximos passos",
    category: "Reuniões",
    area: "todas",
    description: "Transforma anotações soltas em decisões, responsáveis e prazos.",
    whenToUse: "Logo depois da reunião, enquanto o contexto está fresco.",
    text: "Organize estas anotações em: decisões, responsáveis, prazos, pendências e riscos: [anotações].",
    variables: ["anotações"],
    relatedSituations: ["sit-reuniao", "sit-resumir"],
    tags: ["ata", "follow-up"],
    status: "publicado",
  },
  {
    id: "pr-projeto",
    title: "Projeto em etapas, riscos e dependências",
    category: "Projetos",
    area: "todas",
    description: "Uma primeira estrutura de plano para você criticar e ajustar.",
    whenToUse: "No início de um projeto, antes de combinar prazos com outras áreas.",
    text: "Estruture este projeto em etapas, entregas, responsáveis, riscos e dependências: [descrição].",
    variables: ["descrição"],
    relatedSituations: ["sit-projeto"],
    tags: ["projeto", "plano"],
    status: "publicado",
  },
  {
    id: "pr-riscos",
    title: "Mapa de riscos",
    category: "Projetos",
    area: "todas",
    description: "Riscos classificados por probabilidade, impacto e mitigação.",
    whenToUse: "Antes de assumir um compromisso de prazo ou investimento.",
    text: "Identifique riscos para [projeto/decisão], classificando por probabilidade, impacto e possíveis ações de mitigação.",
    variables: ["projeto/decisão"],
    relatedSituations: ["sit-projeto", "sit-decisao-estrategica"],
    tags: ["risco", "mitigação"],
    status: "publicado",
  },
  {
    id: "pr-status",
    title: "Atualização executiva",
    category: "Comunicação",
    area: "todas",
    description: "Resultados, desvios, riscos e decisões necessárias em uma leitura curta.",
    whenToUse: "Quando a liderança precisa decidir, não apenas acompanhar.",
    text: "Transforme estas informações em uma atualização executiva com resultados, desvios, riscos, decisões necessárias e próximos passos: [informações].",
    variables: ["informações"],
    relatedSituations: ["sit-update-executivo"],
    tags: ["status", "executivo"],
    status: "publicado",
  },
  {
    id: "pr-padroes",
    title: "Padrões e inconsistências em dados",
    category: "Dados",
    area: "todas",
    description: "Hipóteses e perguntas a investigar, nunca conclusões prontas.",
    whenToUse: "Com base anonimizada e ferramenta homologada.",
    text: "Com base nesta base anonimizada, identifique padrões, inconsistências, hipóteses e perguntas que precisam ser investigadas: [dados].",
    variables: ["dados"],
    relatedSituations: ["sit-planilha"],
    tags: ["dados", "planilha", "análise"],
    status: "publicado",
  },
  {
    id: "pr-explicar-simples",
    title: "Explicar resultados de forma simples",
    category: "Dados",
    area: "todas",
    description: "Traduz números para quem não tem background técnico.",
    whenToUse: "Quando a análise precisa virar decisão de outra área.",
    text: "Explique estes resultados de forma simples, para alguém sem background técnico: [colar].",
    variables: ["resultados"],
    relatedSituations: ["sit-planilha", "sit-aprender"],
    tags: ["dados", "didático"],
    status: "publicado",
  },
  {
    id: "pr-cenarios",
    title: "Cenários para uma decisão",
    category: "Planejamento",
    area: "todas",
    description: "Prós, contras, riscos e o que ainda precisa ser validado.",
    whenToUse: "Antes de decidir algo relevante, a IA não recomenda a decisão.",
    text: "Apresente cenários, prós, contras, riscos e informações que ainda precisam ser validadas sobre [decisão]. Não recomende uma decisão final.",
    variables: ["decisão"],
    relatedSituations: ["sit-decisao-estrategica"],
    tags: ["decisão", "cenários"],
    status: "publicado",
  },
  {
    id: "pr-comparar",
    title: "Comparar alternativas por critérios",
    category: "Planejamento",
    area: "todas",
    description: "Estrutura a comparação; os pesos e a escolha continuam seus.",
    whenToUse: "Quando há mais de um caminho possível e critérios em disputa.",
    text: "Compare estas alternativas considerando [critérios]. Apresente prós, contras, riscos e informações ainda necessárias: [alternativas].",
    variables: ["critérios", "alternativas"],
    relatedSituations: ["sit-decisao-estrategica", "sit-priorizar"],
    tags: ["comparar", "critérios"],
    status: "publicado",
  },
  {
    id: "pr-feedback",
    title: "Preparar uma conversa de feedback",
    category: "Feedback",
    area: "todas",
    description: "Separa fatos, impactos, perguntas de escuta e encaminhamentos.",
    whenToUse: "Para preparar a conversa. A conversa continua sendo humana.",
    text: "Ajude-me a preparar uma conversa de feedback sobre [situação]. Separe fatos, impactos, perguntas de escuta e possíveis encaminhamentos.",
    variables: ["situação"],
    relatedSituations: ["sit-feedback"],
    tags: ["feedback", "conversa"],
    status: "publicado",
  },
  {
    id: "pr-neutro",
    title: "Organizar pontos de vista de forma neutra",
    category: "Comunicação",
    area: "todas",
    description: "Convergências, divergências e interesses, sem tomar partido.",
    whenToUse: "Para preparar um alinhamento ou uma mediação.",
    text: "Organize de forma neutra os pontos de vista, interesses, convergências e divergências sobre [tema] para apoiar uma conversa de alinhamento.",
    variables: ["tema"],
    relatedSituations: ["sit-alinhamento", "sit-conflito"],
    tags: ["alinhamento", "mediação"],
    status: "publicado",
  },
  {
    id: "pr-organizar",
    title: "Organizar ideias em temas e prioridades",
    category: "Planejamento",
    area: "todas",
    description: "Agrupa, nomeia temas e propõe próximos passos.",
    whenToUse: "Depois de um brainstorming ou de uma rodada de coleta.",
    text: "Organize estas ideias em temas, prioridades, decisões e próximos passos: [conteúdo].",
    variables: ["conteúdo"],
    relatedSituations: ["sit-organizar-ideias", "sit-priorizar"],
    tags: ["organizar", "priorizar"],
    status: "publicado",
  },
  {
    id: "pr-resumo",
    title: "Resumo com decisões e riscos",
    category: "Comunicação",
    area: "todas",
    description: "Contexto, pontos principais, decisões, riscos e próximos passos.",
    whenToUse: "Quando o material é longo e a decisão é curta.",
    text: "Resuma este conteúdo em: contexto, pontos principais, decisões, riscos e próximos passos: [conteúdo].",
    variables: ["conteúdo"],
    relatedSituations: ["sit-resumir"],
    tags: ["resumo"],
    status: "publicado",
  },
  {
    id: "pr-aprender",
    title: "Aprender um tema do zero",
    category: "Aprendizagem",
    area: "todas",
    description: "Explicação progressiva, exemplo aplicado e perguntas de verificação.",
    whenToUse: "Quando você quer entender de verdade, não só ter a resposta.",
    text: "Explique [tema] de forma progressiva, com exemplo aplicado ao meu trabalho e perguntas para verificar meu entendimento. Indique fontes primárias.",
    variables: ["tema"],
    relatedSituations: ["sit-aprender", "sit-duvida-tecnica", "sit-pesquisar"],
    tags: ["aprender", "estudo"],
    status: "publicado",
  },
  {
    id: "pr-critico",
    title: "IA como crítica da sua ideia",
    category: "Criatividade",
    area: "todas",
    description: "Fragilidades, riscos e perguntas difíceis antes da apresentação.",
    whenToUse: "Antes de levar uma proposta para decisão.",
    text: "Aja como um crítico e aponte fragilidades, riscos e perguntas difíceis sobre esta proposta: [proposta].",
    variables: ["proposta"],
    relatedSituations: ["sit-testar-ideia", "sit-apresentacao"],
    tags: ["crítica", "validação"],
    status: "publicado",
  },
  {
    id: "pr-ideias",
    title: "Dez ideias, incluindo as fora do óbvio",
    category: "Criatividade",
    area: "todas",
    description: "Amplia repertório antes da escolha.",
    whenToUse: "Quando as primeiras três ideias são sempre as mesmas.",
    text: "Me dê dez ideias para [objetivo], incluindo pelo menos duas fora do óbvio.",
    variables: ["objetivo"],
    relatedSituations: ["sit-brainstorm"],
    tags: ["ideias", "brainstorm"],
    status: "publicado",
  },
  {
    id: "pr-simplificar-processo",
    title: "Simplificar um processo antes de pedir pessoas",
    category: "Planejamento",
    area: "todas",
    description: "O que pode ser eliminado, simplificado, automatizado ou apoiado por IA.",
    whenToUse: "Antes de solicitar aumento de headcount ou novos recursos.",
    text: "Mapeie este processo e identifique atividades que podem ser eliminadas, simplificadas, automatizadas ou apoiadas por IA. Depois, indique quais etapas continuam exigindo capacidade humana: [descrição].",
    variables: ["descrição"],
    relatedSituations: ["sit-headcount", "sit-processo"],
    tags: ["processo", "capacidade", "headcount"],
    status: "publicado",
  },
];

export const promptById = (id: string) => prompts.find((p) => p.id === id);
