import type { Situation } from "./types";

// Fonte: Guia AI First EMR (2ª edição): Seção 4, Matriz de Decisão.
// Nenhuma regra foi inventada: textos derivam diretamente do guia.

export const situations: Situation[] = [
  {
    id: "sit-duvida-tecnica",
    title: "Tenho uma dúvida técnica ou operacional",
    slug: "duvida-tecnica-ou-operacional",
    summary: "Você precisa entender um conceito, uma regra ou como algo funciona.",
    category: "Aprendizagem",
    area: "todas",
    path: "ia",
    aiRole: "Explica conceitos, resume informações, apresenta exemplos e sugere caminhos.",
    humanRole: "Verificar se a resposta se aplica ao contexto e validar em fontes confiáveis.",
    leadershipTrigger:
      "Quando a dúvida persistir, envolver risco, exceção, política institucional ou impacto relevante.",
    risk: "Aceitar uma resposta incorreta ou inventada como verdadeira.",
    prompt:
      "Explique [tema] para alguém que está aprendendo agora. Traga exemplos e indique fontes oficiais ou primárias para validação.",
    promptIds: ["pr-aprender"],
    videoIds: ["vid-consultou-ia"],
    faqIds: ["faq-confiar", "faq-comecar"],
    exerciseIds: ["ex-porque"],
    tags: ["dúvida", "aprender", "conceito", "como funciona"],
    status: "publicado",
  },
  {
    id: "sit-escrever",
    title: "Preciso escrever um e-mail ou documento",
    slug: "escrever-email-ou-documento",
    summary: "Textos, mensagens, comunicados e documentos do dia a dia.",
    category: "Escrita",
    area: "todas",
    path: "ia",
    aiRole: "Cria uma estrutura ou primeira versão e ajuda a ajustar clareza e tom.",
    humanRole: "Revisar, contextualizar, personalizar e assumir a autoria da mensagem.",
    leadershipTrigger:
      "Quando o conteúdo for sensível, institucional, estratégico ou puder gerar impacto relevante.",
    risk: "Enviar sem revisar ou inserir dados pessoais e sigilosos no prompt.",
    prompt:
      "Crie uma primeira versão de [tipo de texto] para [público], com tom [tom], considerando este contexto: [contexto sem dados sensíveis].",
    promptIds: ["pr-primeira-versao", "pr-reescrever"],
    videoIds: ["vid-copiar-colar"],
    faqIds: ["faq-avisar", "faq-reutilizar"],
    exerciseIds: ["ex-revisao-4"],
    tags: ["e-mail", "texto", "escrever", "documento", "comunicado"],
    status: "publicado",
  },
  {
    id: "sit-apresentacao",
    title: "Vou fazer uma apresentação",
    slug: "criar-apresentacao",
    summary: "Estruturar narrativa, roteiro e slides para um público específico.",
    category: "Comunicação",
    area: "todas",
    path: "ia",
    aiRole: "Sugere narrativa, estrutura de slides, títulos e formas visuais de apresentar o conteúdo.",
    humanRole: "Definir a mensagem central, selecionar informações e validar dados.",
    leadershipTrigger: "Quando a apresentação for executiva, externa ou envolver decisão estratégica.",
    risk: "Priorizar a estética e apresentar informações sem validação.",
    prompt:
      "Sugira uma estrutura de apresentação sobre [tema], para [público], com duração de [tempo] e objetivo de [objetivo].",
    promptIds: ["pr-slides", "pr-critico"],
    videoIds: ["vid-copiar-colar"],
    exerciseIds: ["ex-testar-ideia"],
    tags: ["apresentação", "slides", "deck", "pitch"],
    status: "publicado",
  },
  {
    id: "sit-organizar-ideias",
    title: "Preciso organizar ideias",
    slug: "organizar-ideias",
    summary: "Muita informação solta e nenhuma sequência clara.",
    category: "Organização",
    area: "todas",
    path: "ia",
    aiRole: "Agrupa, categoriza, resume e propõe uma sequência lógica.",
    humanRole: "Definir prioridades, interpretar o contexto e decidir o que faz sentido.",
    leadershipTrigger:
      "Quando a organização influenciar prioridades estratégicas, recursos ou decisões da área.",
    risk: "Transferir integralmente o raciocínio e a priorização para a IA.",
    prompt:
      "Organize estas ideias em temas, prioridades e próximos passos: [colar conteúdo sem informações sensíveis].",
    promptIds: ["pr-organizar"],
    exerciseIds: ["ex-mapear-rotina"],
    tags: ["organizar", "ideias", "priorizar", "bagunça"],
    status: "publicado",
  },
  {
    id: "sit-planilha",
    title: "Tenho uma planilha para analisar",
    slug: "analisar-planilha",
    summary: "Dados, números e uma leitura que precisa ser confiável.",
    category: "Dados",
    area: "todas",
    path: "ia-pessoa",
    aiRole: "Identifica padrões, tendências, inconsistências e pontos fora da curva.",
    humanRole: "Validar a origem e a qualidade da base, conferir cálculos, interpretar o contexto e concluir.",
    leadershipTrigger: "Quando a análise embasar uma decisão financeira, estratégica ou sobre pessoas.",
    risk: "Confiar nos cálculos sem conferir ou utilizar dados sensíveis em ferramenta não homologada.",
    prompt:
      "Com base nesta base anonimizada, identifique padrões, inconsistências, hipóteses e perguntas que precisam ser investigadas: [dados].",
    promptIds: ["pr-padroes", "pr-explicar-simples"],
    videoIds: ["vid-planilha"],
    faqIds: ["faq-dados-alunos"],
    exerciseIds: ["ex-hipoteses"],
    tags: ["planilha", "dados", "análise", "números", "excel"],
    status: "publicado",
  },
  {
    id: "sit-reuniao",
    title: "Vou preparar uma reunião",
    slug: "preparar-reuniao",
    summary: "Pauta, perguntas-guia, tempo e decisões esperadas.",
    category: "Planejamento",
    area: "todas",
    path: "ia",
    aiRole: "Ajuda a estruturar pauta, perguntas-guia, tempos e resultados esperados.",
    humanRole: "Definir o objetivo real, adaptar a pauta e conduzir a conversa.",
    leadershipTrigger: "Quando a reunião envolver decisão fora da sua alçada, conflito ou tema sensível.",
    risk: "Seguir uma pauta genérica sem considerar as pessoas e o contexto.",
    prompt:
      "Crie uma pauta para uma reunião sobre [tema], com objetivo de [objetivo], duração de [tempo] e decisões esperadas.",
    promptIds: ["pr-pauta", "pr-ata"],
    exerciseIds: ["ex-preparar-reuniao"],
    tags: ["reunião", "pauta", "agenda", "encontro"],
    status: "publicado",
  },
  {
    id: "sit-projeto",
    title: "Vou planejar um projeto",
    slug: "planejar-projeto",
    summary: "Etapas, prazos, riscos e dependências.",
    category: "Projetos",
    area: "todas",
    path: "ia-pessoa",
    aiRole: "Sugere etapas, prazos, riscos, dependências e possibilidades de acompanhamento.",
    humanRole: "Avaliar viabilidade, priorizar, definir responsáveis e assumir o plano.",
    leadershipTrigger: "Para aprovação de escopo, prazo, investimento, prioridade ou recursos.",
    risk: "Adotar um cronograma irreal apenas porque foi sugerido pela IA.",
    prompt:
      "Estruture este projeto em etapas, entregas, responsáveis, riscos e dependências: [descrição].",
    promptIds: ["pr-projeto", "pr-riscos"],
    tags: ["projeto", "cronograma", "planejar", "escopo"],
    status: "publicado",
  },
  {
    id: "sit-decisao-estrategica",
    title: "Preciso tomar uma decisão estratégica",
    slug: "decisao-estrategica",
    summary: "Escolha com impacto relevante e mais de um caminho possível.",
    category: "Liderança",
    area: "todas",
    path: "ia-pessoa",
    aiRole: "Amplia os cenários, apresenta prós, contras, riscos e contrapontos.",
    humanRole: "Ponderar o contexto, considerar impactos e tomar a decisão.",
    leadershipTrigger: "Sempre, conforme a alçada, o impacto e a governança da decisão.",
    risk: "Deixar que a IA indique a decisão final ou escolher somente o cenário mais conveniente.",
    prompt:
      "Apresente cenários, prós, contras, riscos e informações que ainda precisam ser validadas sobre [decisão]. Não recomende uma decisão final.",
    promptIds: ["pr-cenarios", "pr-comparar"],
    faqIds: ["faq-discordar"],
    tags: ["decisão", "estratégia", "cenários", "escolha"],
    status: "publicado",
  },
  {
    id: "sit-alinhamento",
    title: "Tenho um alinhamento entre áreas",
    slug: "alinhamento-entre-areas",
    summary: "Interesses diferentes, dependências e a necessidade de um acordo.",
    category: "Comunicação",
    area: "todas",
    path: "pessoa",
    aiRole: "Ajuda a organizar os pontos, preparar a pauta e produzir um resumo neutro.",
    humanRole: "Conduzir a conversa, escutar as partes e construir o acordo.",
    leadershipTrigger: "Quando houver impasse, dependência crítica ou necessidade de decisão superior.",
    risk: "Substituir o diálogo por uma mensagem ou documento gerado pela IA.",
    prompt:
      "Organize de forma neutra os pontos de vista, interesses, convergências e divergências sobre [tema] para apoiar uma conversa de alinhamento.",
    promptIds: ["pr-neutro"],
    videoIds: ["vid-pessoa-primeiro"],
    tags: ["alinhamento", "áreas", "acordo", "dependência"],
    status: "publicado",
  },
  {
    id: "sit-conflito",
    title: "Tenho um conflito para resolver",
    slug: "conflito",
    summary: "Tensão entre pessoas, times ou pontos de vista.",
    category: "Pessoas",
    area: "todas",
    path: "pessoa",
    aiRole: "Ajuda a preparar perguntas neutras e organizar a abordagem da conversa.",
    humanRole: "Escutar as partes, mediar, cuidar da relação e construir encaminhamentos.",
    leadershipTrigger: "Quando houver escalada, risco, desequilíbrio de poder ou necessidade de mediação.",
    risk: "Usar a IA para evitar a conversa ou concluir quem está certo sem escutar as pessoas.",
    prompt:
      "Sugira perguntas neutras para compreender os diferentes pontos de vista sobre [tema] e preparar uma conversa respeitosa.",
    promptIds: ["pr-neutro"],
    videoIds: ["vid-pessoa-primeiro", "vid-colega-lideranca"],
    tags: ["conflito", "tensão", "mediação", "desentendimento"],
    status: "publicado",
  },
  {
    id: "sit-feedback",
    title: "Preciso dar um feedback",
    slug: "dar-feedback",
    summary: "Uma conversa que precisa de presença, escuta e cuidado.",
    category: "Pessoas",
    area: "todas",
    path: "pessoa",
    aiRole: "Ajuda a organizar fatos, impactos, perguntas e possíveis encaminhamentos.",
    humanRole: "Dar o feedback com presença, empatia, escuta e responsabilidade.",
    leadershipTrigger: "Quando envolver desempenho formal, recorrência, risco ou consequência para a pessoa.",
    risk: "Enviar um feedback gerado por IA sem uma conversa real ou compartilhar dados pessoais indevidamente.",
    prompt:
      "Ajude-me a preparar uma conversa de feedback sobre [situação]. Separe fatos, impactos, perguntas de escuta e possíveis encaminhamentos.",
    promptIds: ["pr-feedback"],
    videoIds: ["vid-feedback", "vid-pessoa-primeiro"],
    faqIds: ["faq-feedback-dificil"],
    exerciseIds: ["ex-simular-conversa"],
    tags: ["feedback", "conversa difícil", "desempenho", "1:1"],
    status: "publicado",
  },
  {
    id: "sit-avaliacao",
    title: "Estou em uma avaliação de desempenho",
    slug: "avaliacao-de-desempenho",
    summary: "Critérios, evidências e uma devolutiva que é humana.",
    category: "Pessoas",
    area: "gente-gestao",
    path: "pessoa",
    aiRole:
      "Pode apoiar a organização de critérios, evidências previamente registradas e perguntas para a devolutiva, seguindo as regras institucionais.",
    humanRole:
      "Avaliar com julgamento humano, considerar contexto, realizar a devolutiva e assumir a avaliação.",
    leadershipTrigger:
      "Conforme o rito da Avaliação de Desempenho e sempre que houver dúvida, divergência ou consequência relevante.",
    risk:
      "Permitir que a IA atribua nota, classifique a pessoa ou receba dados pessoais em ambiente não autorizado.",
    prompt:
      "Crie uma estrutura para organizar evidências objetivas de desempenho por competência, sem atribuir nota ou recomendar decisão.",
    videoIds: ["vid-promocao"],
    faqIds: ["faq-avaliacao-desempenho", "faq-promocao"],
    tags: ["avaliação", "desempenho", "evidências", "devolutiva"],
    status: "publicado",
  },
  {
    id: "sit-promocao",
    title: "Preciso avaliar uma promoção",
    slug: "promocao",
    summary: "Mérito, equidade, orçamento e impacto organizacional.",
    category: "Pessoas",
    area: "gente-gestao",
    path: "pessoa",
    aiRole:
      "Pode apoiar a organização dos critérios e a análise estrutural, desde que não receba dados pessoais sem autorização.",
    humanRole:
      "Avaliar mérito, contexto, equidade, orçamento e impacto organizacional; tomar a decisão conforme a governança.",
    leadershipTrigger:
      "Sempre, envolvendo a liderança responsável e Gente & Gestão conforme o processo vigente.",
    risk: "Basear a promoção em ranking, recomendação automática ou análise exclusiva da IA.",
    prompt:
      "Crie um checklist de critérios objetivos que devem ser considerados em uma análise de promoção. Não avalie pessoas nem recomende uma decisão.",
    videoIds: ["vid-promocao"],
    faqIds: ["faq-promocao"],
    tags: ["promoção", "mérito", "carreira", "cargo"],
    status: "publicado",
  },
  {
    id: "sit-reconhecimento",
    title: "Quero reconhecer alguém do time",
    slug: "merito-e-reconhecimento",
    summary: "Reconhecimento específico, com evidência e sinceridade.",
    category: "Liderança",
    area: "todas",
    path: "pessoa",
    aiRole: "Ajuda a estruturar uma comunicação de reconhecimento ou organizar critérios previamente definidos.",
    humanRole: "Definir quem será reconhecido, por qual motivo e qual será a forma adequada de valorização.",
    leadershipTrigger: "Conforme a política, o orçamento e a governança de reconhecimento.",
    risk: "Produzir um reconhecimento genérico, sem evidências ou sem sinceridade.",
    prompt:
      "Ajude-me a escrever um reconhecimento específico e genuíno sobre [entrega/comportamento], destacando o impacto gerado.",
    tags: ["reconhecimento", "mérito", "elogio", "valorização"],
    status: "publicado",
  },
  {
    id: "sit-desligamento",
    title: "Estou diante de um desligamento",
    slug: "desligamento",
    summary: "Decisão sensível, conduzida com Gente & Gestão.",
    category: "Pessoas",
    area: "gente-gestao",
    path: "pessoa",
    aiRole:
      "Não participa da decisão. Pode ser utilizada apenas em materiais genéricos ou checklists institucionais previamente aprovados.",
    humanRole:
      "Avaliar o caso, decidir, planejar e conduzir o processo com cuidado, respeito e participação de Gente & Gestão.",
    leadershipTrigger: "Sempre, antes de qualquer comunicação ou encaminhamento.",
    risk:
      "Compartilhar dados do caso, pedir que a IA recomende o desligamento ou gerar uma justificativa automática.",
    prompt: "Não utilize IA com informações do caso. Consulte Gente & Gestão e siga o fluxo institucional.",
    faqIds: ["faq-promocao"],
    tags: ["desligamento", "demissão", "sensível"],
    status: "publicado",
  },
  {
    id: "sit-headcount",
    title: "Quero pedir aumento de headcount",
    slug: "aumento-de-headcount",
    summary: "Antes de pedir pessoas, olhe para processo, prioridade e capacidade.",
    category: "Liderança",
    area: "todas",
    path: "ia-pessoa",
    aiRole:
      "Ajuda a mapear processos, volume de atividades, gargalos, possibilidades de simplificação, automação e uso de IA.",
    humanRole:
      "Avaliar capacidade, prioridades, competências necessárias e decidir se a necessidade é realmente de novas pessoas.",
    leadershipTrigger:
      "Sempre, conforme a governança de estrutura, orçamento e participação de Gente & Gestão.",
    risk:
      "Solicitar aumento de headcount sem antes avaliar processo, prioridades, automação e melhor uso da capacidade atual.",
    prompt:
      "Mapeie este processo e identifique atividades que podem ser eliminadas, simplificadas, automatizadas ou apoiadas por IA. Depois, indique quais etapas continuam exigindo capacidade humana: [descrição].",
    promptIds: ["pr-simplificar-processo"],
    videoIds: ["vid-headcount"],
    exerciseIds: ["ex-simplificar"],
    tags: ["headcount", "contratação", "capacidade", "time", "vaga"],
    status: "publicado",
  },
  {
    id: "sit-dados-sensiveis",
    title: "Posso colocar esse dado na IA?",
    slug: "uso-de-informacoes-sigilosas",
    summary: "Dúvida sobre dados pessoais, estratégicos ou confidenciais.",
    category: "Segurança",
    area: "todas",
    path: "pessoa",
    aiRole:
      "Só pode apoiar quando houver autorização, ferramenta homologada e tratamento adequado dos dados.",
    humanRole:
      "Avaliar se a informação pode ser utilizada, remover identificadores e proteger a confidencialidade.",
    leadershipTrigger:
      "Sempre que houver dúvida sobre dado pessoal, estratégico, financeiro, jurídico ou confidencial.",
    risk:
      "Inserir dados sensíveis, credenciais, contratos ou informações não públicas em ferramenta não autorizada.",
    prompt:
      "Antes de formular o prompt, confirme a autorização e remova nomes, CPFs, e-mails, credenciais e outros identificadores.",
    videoIds: ["vid-informacao-ia"],
    faqIds: ["faq-dados-alunos", "faq-ferramentas", "faq-uso-inadequado"],
    tags: ["segurança", "dados", "sigilo", "LGPD", "confidencial"],
    status: "publicado",
  },
  {
    id: "sit-contratos",
    title: "Tenho um contrato ou documento jurídico",
    slug: "contratos-e-juridico",
    summary: "Documentos vinculantes exigem revisão jurídica.",
    category: "Segurança",
    area: "todas",
    path: "pessoa",
    aiRole: "Pode sinalizar pontos gerais apenas em fluxo autorizado.",
    humanRole: "Garantir revisão jurídica e proteger o documento.",
    leadershipTrigger: "Sempre que o documento for sigiloso, vinculante ou relevante.",
    risk: "Tratar a análise da IA como parecer jurídico.",
    prompt:
      "Crie um checklist genérico de pontos que costumam ser avaliados em contratos deste tipo, sem analisar dados sigilosos.",
    faqIds: ["faq-ferramentas"],
    tags: ["contrato", "jurídico", "cláusula"],
    status: "publicado",
  },
  {
    id: "sit-incidente",
    title: "Acho que compartilhei algo indevido",
    slug: "suspeita-de-compartilhamento-indevido",
    summary: "Suspeita de exposição de informação sensível em uma ferramenta de IA.",
    category: "Segurança",
    area: "todas",
    path: "pessoa",
    aiRole: "Não deve ser utilizada para avaliar sozinha o incidente.",
    humanRole: "Interromper o uso e comunicar imediatamente.",
    leadershipTrigger: "Sempre, seguindo o fluxo institucional.",
    risk: "Tentar resolver ou esconder o incidente sem comunicar.",
    prompt:
      "Não insira novamente os dados. Procure imediatamente Engenharia/Tecnologia e Gente & Gestão.",
    faqIds: ["faq-uso-inadequado"],
    tags: ["incidente", "vazamento", "erro", "segurança"],
    status: "publicado",
  },
  {
    id: "sit-resumir",
    title: "Preciso resumir um conteúdo longo",
    slug: "resumir-conteudos",
    summary: "Artigos, relatórios, reuniões ou conversas extensas.",
    category: "Organização",
    area: "todas",
    path: "ia",
    aiRole: "Identifica temas centrais, decisões, riscos e próximos passos.",
    humanRole:
      "Conferir se os pontos importantes foram preservados e se o resumo representa corretamente o conteúdo.",
    leadershipTrigger:
      "Quando o material envolver decisão estratégica, informação sensível ou compromisso institucional.",
    risk: "Perder nuances importantes ou assumir que o resumo substitui a leitura completa.",
    prompt: "Resuma este conteúdo em: contexto, pontos principais, decisões, riscos e próximos passos: [conteúdo].",
    promptIds: ["pr-resumo"],
    exerciseIds: ["ex-resumo-relampago"],
    tags: ["resumo", "relatório", "ata", "leitura"],
    status: "publicado",
  },
  {
    id: "sit-traduzir",
    title: "Preciso traduzir um conteúdo",
    slug: "traduzir-conteudos",
    summary: "Tradução com fidelidade de sentido e adequação de tom.",
    category: "Escrita",
    area: "todas",
    path: "ia",
    aiRole: "Produz uma primeira tradução e pode adaptar tom e linguagem ao público.",
    humanRole: "Revisar termos técnicos, contexto cultural e fidelidade da mensagem.",
    leadershipTrigger: "Em documentos oficiais, jurídicos, comerciais, acadêmicos ou externos.",
    risk: "Utilizar uma tradução incorreta ou inadequada ao contexto.",
    prompt: "Traduza este conteúdo para [idioma], preservando o sentido e adaptando o tom para [público]: [texto].",
    tags: ["tradução", "idioma", "inglês"],
    status: "publicado",
  },
  {
    id: "sit-revisar",
    title: "Quero revisar um texto ou entrega",
    slug: "revisar-textos-e-entregas",
    summary: "Uma segunda leitura crítica antes de entregar.",
    category: "Escrita",
    area: "todas",
    path: "ia-pessoa",
    aiRole: "Identifica erros, falta de clareza, inconsistências e oportunidades de melhoria.",
    humanRole: "Decidir quais ajustes fazem sentido e validar a versão final.",
    leadershipTrigger: "Quando a entrega for externa, executiva, estratégica ou sensível.",
    risk: "Aceitar todas as alterações sem considerar intenção e contexto.",
    prompt:
      "Revise este conteúdo e identifique erros, ambiguidades, repetições e pontos que precisam de mais clareza: [texto].",
    promptIds: ["pr-revisar"],
    exerciseIds: ["ex-revisao-4"],
    tags: ["revisão", "texto", "qualidade"],
    status: "publicado",
  },
  {
    id: "sit-processo",
    title: "Preciso documentar ou simplificar um processo",
    slug: "documentar-processo",
    summary: "Transformar prática real em fluxo claro, e enxergar o que dá para simplificar.",
    category: "Organização",
    area: "operacoes",
    path: "ia",
    aiRole: "Estrutura etapas, responsáveis, entradas, saídas, riscos e pontos de controle.",
    humanRole: "Confirmar como o processo realmente funciona e validar com as pessoas envolvidas.",
    leadershipTrigger: "Quando houver mudança de responsabilidade, risco, sistema ou política.",
    risk: "Documentar um processo idealizado que não representa a prática.",
    prompt:
      "Transforme esta descrição em um fluxo de processo com etapas, responsáveis, entradas, saídas e riscos: [descrição].",
    promptIds: ["pr-simplificar-processo"],
    exerciseIds: ["ex-simplificar"],
    tags: ["processo", "documentação", "fluxo", "operação"],
    status: "publicado",
  },
  {
    id: "sit-pesquisar",
    title: "Quero pesquisar referências ou tendências",
    slug: "pesquisar-referencias",
    summary: "Mapear o que já existe antes de construir do zero.",
    category: "Pesquisa",
    area: "todas",
    path: "ia",
    aiRole: "Ajuda a mapear conceitos, abordagens, referências e perguntas de pesquisa.",
    humanRole: "Conferir fontes, datas, autoria e aplicabilidade à realidade da EMR.",
    leadershipTrigger: "Quando a pesquisa embasar investimento, política ou decisão estratégica.",
    risk: "Utilizar referências inexistentes, desatualizadas ou sem fonte confiável.",
    prompt:
      "Apresente uma visão inicial sobre [tema], indique fontes primárias e separe fatos, tendências e hipóteses.",
    promptIds: ["pr-aprender"],
    faqIds: ["faq-confiar"],
    tags: ["pesquisa", "referências", "benchmark", "tendências"],
    status: "publicado",
  },
  {
    id: "sit-aprender",
    title: "Quero aprender um assunto novo",
    slug: "aprender-tema-novo",
    summary: "Do zero ao entendimento aplicado ao seu trabalho.",
    category: "Aprendizagem",
    area: "todas",
    path: "ia",
    aiRole: "Explica conceitos, cria exemplos, exercícios e trilhas de estudo.",
    humanRole: "Praticar, verificar informações e buscar especialistas quando necessário.",
    leadershipTrigger: "Quando o tema envolver risco, conformidade ou conhecimento técnico especializado.",
    risk: "Confundir uma explicação simples com domínio real do assunto.",
    prompt:
      "Explique [tema] de forma progressiva, com exemplo aplicado ao meu trabalho e perguntas para verificar meu entendimento.",
    promptIds: ["pr-aprender", "pr-explicar-simples"],
    faqIds: ["faq-aprender", "faq-comecar"],
    exerciseIds: ["ex-porque", "ex-traduza"],
    tags: ["aprender", "estudo", "formação", "novo tema"],
    status: "publicado",
  },
  {
    id: "sit-negociar",
    title: "Vou negociar",
    slug: "negociacao",
    summary: "Preparação ajuda; a conversa é sua.",
    category: "Comunicação",
    area: "comercial",
    path: "pessoa",
    aiRole: "Ajuda a antecipar objeções, preparar argumentos e simular cenários.",
    humanRole: "Conduzir a conversa, escutar, interpretar sinais e fechar o acordo dentro da sua alçada.",
    leadershipTrigger: "Conforme o valor, a alçada, o risco e as condições envolvidas.",
    risk: "Negociar por meio da IA sem leitura humana, contexto ou autorização.",
    prompt:
      "Simule possíveis objeções para esta negociação e sugira perguntas e alternativas de resposta: [contexto sem dados sigilosos].",
    exerciseIds: ["ex-simular-conversa"],
    videoIds: ["vid-pessoa-primeiro"],
    tags: ["negociação", "objeções", "proposta", "cliente"],
    status: "publicado",
  },
  {
    id: "sit-testar-ideia",
    title: "Quero testar uma ideia antes de apresentar",
    slug: "testar-uma-ideia",
    summary: "Descobrir as fragilidades antes que outra pessoa descubra.",
    category: "Criatividade",
    area: "todas",
    path: "ia",
    aiRole: "Atua como crítica, aponta fragilidades e antecipa objeções.",
    humanRole: "Avaliar os contrapontos e fortalecer a proposta.",
    leadershipTrigger: "Quando a ideia tiver alto impacto ou depender de decisão executiva.",
    risk: "Ajustar a proposta apenas para agradar ou ignorar críticas relevantes.",
    prompt:
      "Atue como um crítico e identifique fragilidades, riscos e perguntas difíceis sobre esta proposta: [proposta].",
    promptIds: ["pr-critico", "pr-ideias"],
    exerciseIds: ["ex-testar-ideia"],
    tags: ["ideia", "proposta", "crítica", "validação"],
    status: "publicado",
  },
  {
    id: "sit-brainstorm",
    title: "Preciso de ideias novas",
    slug: "brainstorming",
    summary: "Ampliar repertório antes de escolher um caminho.",
    category: "Criatividade",
    area: "todas",
    path: "ia",
    aiRole: "Gera possibilidades, alternativas e ideias fora do padrão inicial.",
    humanRole: "Selecionar, combinar, adaptar e decidir quais ideias fazem sentido.",
    leadershipTrigger:
      "Quando as ideias dependerem de investimento, mudança estratégica ou compromisso institucional.",
    risk: "Confundir quantidade de ideias com qualidade ou viabilidade.",
    prompt: "Gere 15 ideias para [desafio], incluindo opções simples, ousadas e de baixo custo.",
    promptIds: ["pr-ideias"],
    exerciseIds: ["ex-brainstorm"],
    tags: ["ideias", "brainstorm", "criatividade", "campanha"],
    status: "publicado",
  },
  {
    id: "sit-priorizar",
    title: "Preciso priorizar demandas",
    slug: "priorizar-demandas",
    summary: "Muita coisa na fila e critérios pouco claros.",
    category: "Planejamento",
    area: "todas",
    path: "ia-pessoa",
    aiRole: "Ajuda a organizar demandas por impacto, urgência, esforço e risco.",
    humanRole: "Aplicar critérios estratégicos e decidir o que será priorizado.",
    leadershipTrigger: "Quando houver disputa de recursos ou impactos entre áreas.",
    risk: "Tratar a priorização como cálculo automático.",
    prompt:
      "Organize estas demandas em uma matriz de impacto, urgência, esforço e risco. Não defina a prioridade final.",
    promptIds: ["pr-organizar"],
    tags: ["prioridade", "backlog", "fila", "demandas"],
    status: "publicado",
  },
  {
    id: "sit-indicadores",
    title: "Preciso criar indicadores",
    slug: "criar-indicadores",
    summary: "Medir o que importa, não apenas o que é fácil.",
    category: "Dados",
    area: "todas",
    path: "ia-pessoa",
    aiRole: "Sugere métricas, fórmulas, periodicidade e formas de leitura.",
    humanRole: "Definir o que realmente representa sucesso e validar a memória de cálculo.",
    leadershipTrigger: "Quando o indicador fizer parte da gestão corporativa ou da avaliação de pessoas.",
    risk: "Medir o que é fácil, mas não o que importa.",
    prompt:
      "Sugira indicadores para acompanhar [objetivo], com definição, fórmula, fonte, periodicidade e interpretação.",
    tags: ["indicadores", "kpi", "métricas", "meta"],
    status: "publicado",
  },
  {
    id: "sit-update-executivo",
    title: "Preciso preparar uma atualização executiva",
    slug: "atualizacao-executiva",
    summary: "Status, resultados, riscos e decisões necessárias.",
    category: "Comunicação",
    area: "todas",
    path: "ia",
    aiRole: "Organiza status, resultados, riscos, decisões e próximos passos.",
    humanRole: "Selecionar o que é relevante e assumir a narrativa executiva.",
    leadershipTrigger: "Quando houver problema crítico, mudança de escopo ou necessidade de decisão.",
    risk: "Omitir riscos ou produzir uma atualização excessivamente operacional.",
    prompt:
      "Transforme estas informações em uma atualização executiva com resultados, desvios, riscos, decisões necessárias e próximos passos.",
    promptIds: ["pr-status"],
    tags: ["executivo", "status", "report", "diretoria"],
    status: "publicado",
  },
];

export const situationBySlug = (slug: string) => situations.find((s) => s.slug === slug);
export const situationById = (id: string) => situations.find((s) => s.id === id);
