import type { VideoItem } from "./types";

// Biblioteca audiovisual. Os vídeos ainda não foram produzidos:
// status "em-breve" e url null. Nada é inventado: apenas o tema já definido.

export const videos: VideoItem[] = [
  {
    id: "vid-consultou-ia",
    title: "Você já consultou a IA?",
    duration: "2 min",
    category: "Mentalidade",
    behavior: "Avaliar se a IA pode ajudar",
    area: "todas",
    description: "A pergunta que muda o ponto de partida de qualquer tarefa.",
    url: null,
    relatedSituations: ["sit-duvida-tecnica", "sit-aprender"],
    relatedPrompts: ["pr-aprender"],
    relatedCases: [],
    status: "em-breve",
  },
  {
    id: "vid-feedback",
    title: "A IA pode me ajudar a preparar um feedback?",
    duration: "3 min",
    category: "Pessoas",
    behavior: "Preparar com IA, conversar com presença",
    area: "todas",
    description: "Onde a IA ajuda na preparação e onde a conversa é inteiramente sua.",
    url: null,
    relatedSituations: ["sit-feedback"],
    relatedPrompts: ["pr-feedback"],
    relatedCases: [],
    status: "em-breve",
  },
  {
    id: "vid-planilha",
    title: "Como analisar uma planilha com IA?",
    duration: "4 min",
    category: "Dados",
    behavior: "Validar criticamente",
    area: "todas",
    description: "Padrões, inconsistências e o que você precisa conferir antes de concluir.",
    url: null,
    relatedSituations: ["sit-planilha"],
    relatedPrompts: ["pr-padroes"],
    relatedCases: [],
    status: "em-breve",
  },
  {
    id: "vid-promocao",
    title: "Quem decide uma promoção?",
    duration: "2 min",
    category: "Pessoas",
    behavior: "Assumir a responsabilidade pela decisão",
    area: "gente-gestao",
    description: "Decisões sobre pessoas continuam humanas, com governança e contexto.",
    url: null,
    relatedSituations: ["sit-promocao", "sit-avaliacao"],
    relatedPrompts: [],
    relatedCases: [],
    status: "em-breve",
  },
  {
    id: "vid-informacao-ia",
    title: "Posso colocar essa informação na IA?",
    duration: "3 min",
    category: "Segurança",
    behavior: "Proteger informações",
    area: "todas",
    description: "O teste mental do café cheio e o que fazer na dúvida.",
    url: null,
    relatedSituations: ["sit-dados-sensiveis"],
    relatedPrompts: [],
    relatedCases: [],
    status: "em-breve",
  },
  {
    id: "vid-headcount",
    title: "Precisamos mesmo aumentar o headcount?",
    duration: "4 min",
    category: "Liderança",
    behavior: "Analisar capacidade antes de pedir pessoas",
    area: "todas",
    description: "As perguntas de capacidade que antecedem a solicitação de estrutura.",
    url: null,
    relatedSituations: ["sit-headcount"],
    relatedPrompts: ["pr-simplificar-processo"],
    relatedCases: [],
    status: "em-breve",
  },
  {
    id: "vid-copiar-colar",
    title: "Copiar e colar não é AI First",
    duration: "2 min",
    category: "Mentalidade",
    behavior: "Adaptar ao contexto",
    area: "todas",
    description: "Por que a validação é parte do trabalho, e não uma etapa opcional.",
    url: null,
    relatedSituations: ["sit-escrever", "sit-revisar"],
    relatedPrompts: ["pr-revisar"],
    relatedCases: [],
    status: "em-breve",
  },
  {
    id: "vid-pessoa-primeiro",
    title: "Quando procurar uma pessoa primeiro?",
    duration: "3 min",
    category: "Mentalidade",
    behavior: "Aumentar a presença humana na dúvida",
    area: "todas",
    description: "A régua de ouro: quanto mais a decisão afeta alguém, mais presença humana.",
    url: null,
    relatedSituations: ["sit-feedback", "sit-conflito", "sit-alinhamento"],
    relatedPrompts: ["pr-neutro"],
    relatedCases: [],
    status: "em-breve",
  },
  {
    id: "vid-colega-lideranca",
    title: "Quando procurar um colega ou a liderança?",
    duration: "2 min",
    category: "Colaboração",
    behavior: "Pedir ajuda quando necessário",
    area: "todas",
    description: "AI First não reduz colaboração: melhora o ponto de partida da conversa.",
    url: null,
    relatedSituations: ["sit-conflito", "sit-decisao-estrategica"],
    relatedPrompts: [],
    relatedCases: [],
    status: "em-breve",
  },
];

export const videoById = (id: string) => videos.find((v) => v.id === id);
