ALTER TABLE "RetroCard" ADD COLUMN "kind" TEXT NOT NULL DEFAULT 'note';
ALTER TABLE "RetroCard" ADD COLUMN "shape" TEXT;
ALTER TABLE "RetroCard" ADD COLUMN "shapeStyle" TEXT;
ALTER TABLE "RetroCard" ADD COLUMN "width" DOUBLE PRECISION;
ALTER TABLE "RetroCard" ADD COLUMN "height" DOUBLE PRECISION;
