apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-store-hml
spec:
  provider:
    vault:
      server: "https://vault.eumedicoresidente.com.br"
      path: "SOA-HML"   # mount KV v2
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes-hml"
          role: "soa-hml-eso"
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legends-legends-secrets
  namespace: legends
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store-hml
    kind: ClusterSecretStore
  target:
    name: legends-legends-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: legends
        conversionStrategy: Default
        decodingStrategy: None
