// Catálogo de ilustrações 3D do centro do selo. Assets CC0 do 3dicons.co,
// versionados em apps/web/public/badge-art/<key>.png.
// `color` é a cor de acento do medalhão escolhida para combinar com a arte.

export interface BadgeArt {
  key: string
  label: string
  src: string
  color: string
}

function art(key: string, label: string, color: string): BadgeArt {
  return { key, label, src: `/badge-art/${key}.png`, color }
}

// As chaves batem com os nomes de arquivo do 3dicons (estilo front/color),
// salvos via apps/web/scripts/fetch-badge-art.mjs. Exceção: `shield` é baixado
// do `sheild` (grafia do 3dicons) e salvo como shield.png — ver o script.
export const BADGE_ART: BadgeArt[] = [
  art('rocket', 'Foguete', '#fb923c'),
  art('trophy', 'Troféu', '#facc15'),
  art('medal', 'Medalha', '#fb7185'),
  art('star', 'Estrela', '#facc15'),
  art('ribbon', 'Prêmio', '#f59e0b'),
  art('fire', 'Fogo', '#f97316'),
  art('bulb', 'Ideia', '#fbbf24'),
  art('shield', 'Escudo', '#52fba2'),
  art('target', 'Alvo', '#f87171'),
  art('link', 'Conexão', '#38bdf8'),
  art('cube', 'Cubo', '#60a5fa'),
  art('calendar', 'Calendário', '#2dd4bf'),
  art('heart', 'Coração', '#fb7185'),
  art('flash', 'Raio', '#fcd34d'),
  art('puzzle', 'Quebra-cabeça', '#34d399'),
  art('flag', 'Bandeira', '#f472b6'),
  art('notebook', 'Caderno', '#818cf8'),
  art('tool', 'Ferramenta', '#94a3b8'),
  art('chart', 'Gráfico', '#22c55e'),
  art('key', 'Chave', '#fbbf24'),
  art('lock', 'Cadeado', '#a78bfa'),
  art('computer', 'Computador', '#60a5fa'),
  art('lab', 'Laboratório', '#c4b5fd'),
  art('setting', 'Engrenagem', '#94a3b8'),
  art('3d', '3D', '#60a5fa'),
  art('3d-coin', 'Moeda 3D', '#facc15'),
  art('at', 'Arroba', '#fbbf24'),
  art('axe', 'Machado', '#f87171'),
  art('back', 'Voltar', '#22d3ee'),
  art('backward', 'Retroceder', '#c4b5fd'),
  art('bag', 'Mochila', '#818cf8'),
  art('ball', 'Bola', '#fb923c'),
  art('battery', 'Bateria', '#34d399'),
  art('bell', 'Sino', '#fbbf24'),
  art('blender', 'Blender', '#fb923c'),
  art('bookmark', 'Marcador', '#38bdf8'),
  art('bookmark-fav', 'Marcador favorito', '#52fba2'),
  art('boy', 'Menino', '#a78bfa'),
  art('brush', 'Pincel', '#a78bfa'),
  art('bucket', 'Balde', '#2dd4bf'),
  art('calculator', 'Calculadora', '#60a5fa'),
  art('camera', 'Câmera', '#60a5fa'),
  art('can', 'Lata', '#fbbf24'),
  art('candle', 'Vela', '#f87171'),
  art('cap', 'Boné', '#22d3ee'),
  art('card', 'Cartão', '#c4b5fd'),
  art('chat', 'Chat', '#38bdf8'),
  art('chat-bubble', 'Balão de chat', '#2dd4bf'),
  art('chat-text', 'Mensagem', '#60a5fa'),
  art('chess', 'Xadrez', '#94a3b8'),
  art('circle', 'Círculo', '#60a5fa'),
  art('clock', 'Relógio', '#38bdf8'),
  art('color-palette', 'Paleta', '#f472b6'),
  art('copy', 'Copiar', '#a78bfa'),
  art('cup', 'Caneca', '#f472b6'),
  art('dollar', 'Dólar', '#34d399'),
  art('euro', 'Euro', '#38bdf8'),
  art('eth', 'Ethereum', '#a78bfa'),
  art('explorer', 'Bússola', '#fbbf24'),
  art('eyedropper', 'Conta-gotas', '#22d3ee'),
  art('fav-folder', 'Pasta favorita', '#22d3ee'),
  art('figma', 'Figma', '#a78bfa'),
  art('file', 'Arquivo', '#818cf8'),
  art('file-fav', 'Arquivo favorito', '#f59e0b'),
  art('file-plus', 'Novo arquivo', '#fb923c'),
  art('file-text', 'Documento', '#facc15'),
  art('folder', 'Pasta', '#fb7185'),
  art('forward', 'Avançar', '#38bdf8'),
  art('gift', 'Presente', '#fb7185'),
  art('gift-box', 'Caixa de presente', '#f472b6'),
  art('girl', 'Menina', '#f472b6'),
  art('glass', 'Taça', '#2dd4bf'),
  art('gloves', 'Luvas', '#52fba2'),
  art('gym', 'Halter', '#f87171'),
  art('headphone', 'Fone', '#818cf8'),
  art('leaf', 'Folha', '#34d399'),
  art('location', 'Localização', '#f87171'),
  art('locker', 'Armário', '#c4b5fd'),
  art('magic-trick', 'Mágica', '#818cf8'),
  art('mail', 'E-mail', '#38bdf8'),
  art('map-pin', 'Pino do mapa', '#fb7185'),
  art('megaphone', 'Megafone', '#fb923c'),
  art('mic', 'Microfone', '#f87171'),
  art('mobile', 'Celular', '#2dd4bf'),
  art('money', 'Dinheiro', '#34d399'),
  art('money-bag', 'Saco de dinheiro', '#34d399'),
  art('moon', 'Lua', '#818cf8'),
  art('music', 'Música', '#a78bfa'),
  art('new-folder', 'Nova pasta', '#60a5fa'),
  art('next', 'Próximo', '#34d399'),
  art('notify-heart', 'Curtida', '#f472b6'),
  art('paint-brush', 'Pincel de tinta', '#f472b6'),
  art('paint-kit', 'Kit de pintura', '#34d399'),
  art('pause', 'Pausar', '#c4b5fd'),
  art('pencil', 'Lápis', '#fbbf24'),
  art('phone-ringing', 'Telefone', '#34d399'),
  art('picture', 'Imagem', '#34d399'),
  art('pin', 'Alfinete', '#f87171'),
  art('play', 'Play', '#fb7185'),
  art('plus', 'Mais', '#34d399'),
  art('pound', 'Libra', '#facc15'),
  art('roll-brush', 'Rolo de tinta', '#fbbf24'),
  art('rupee', 'Rúpia', '#fb923c'),
  art('scissor', 'Tesoura', '#f87171'),
  art('shocks', 'Meias', '#60a5fa'),
  art('sphere', 'Esfera', '#38bdf8'),
  art('sun', 'Sol', '#fbbf24'),
  art('takeaway-cup', 'Copo', '#f87171'),
  art('tea-cup', 'Xícara', '#22d3ee'),
  art('text', 'Texto', '#94a3b8'),
  art('thumb-down', 'Não curtir', '#f87171'),
  art('thumb-up', 'Curtir', '#34d399'),
  art('tick', 'Check', '#34d399'),
  art('toggle', 'Interruptor', '#facc15'),
  art('trash-can', 'Lixeira', '#fb7185'),
  art('travel', 'Viagem', '#38bdf8'),
  art('umbrella', 'Guarda-chuva', '#f472b6'),
  art('video-camera', 'Filmadora', '#f87171'),
  art('wallet', 'Carteira', '#f59e0b'),
  art('wifi', 'Wi-Fi', '#38bdf8'),
  art('yuan', 'Yuan', '#f87171'),
  art('zoom', 'Zoom', '#34d399'),
  // Extras do CDN do 3dicons (não estavam na curadoria inicial).
  art('candy', 'Doce', '#f472b6'),
  art('snowflake', 'Floco de neve', '#38bdf8'),
  art('star-2', 'Estrela cintilante', '#fbbf24'),
  art('phone-only', 'Telefone fixo', '#2dd4bf'),
  art('phone-incoming', 'Chamada recebida', '#34d399'),
  art('phone-outgoing', 'Chamada feita', '#38bdf8'),
  art('phone-missing', 'Chamada perdida', '#f87171'),
  art('phone-end', 'Chamada encerrada', '#fb7185'),

  // Microsoft Fluent Emoji (MIT) — estilo 3D glossy, complementa o 3dicons.
  // Chaves com prefixo `fe-`; baixadas por scripts/fetch-fluent-emoji.mjs.
  art('fe-trophy', 'Troféu de ouro', '#facc15'),
  art('fe-medal-gold', 'Medalha de ouro', '#facc15'),
  art('fe-medal-silver', 'Medalha de prata', '#cbd5e1'),
  art('fe-medal-bronze', 'Medalha de bronze', '#d97706'),
  art('fe-medal-sports', 'Medalha esportiva', '#f59e0b'),
  art('fe-medal-honor', 'Medalha de honra', '#ef4444'),
  art('fe-crown', 'Coroa', '#facc15'),
  art('fe-star-glow', 'Estrela brilhante', '#fcd34d'),
  art('fe-star', 'Estrela dourada', '#facc15'),
  art('fe-shooting-star', 'Estrela cadente', '#38bdf8'),
  art('fe-sparkles', 'Brilhos', '#fbbf24'),
  art('fe-hundred', 'Cem pontos', '#ef4444'),
  art('fe-check', 'Concluído', '#22c55e'),
  art('fe-party', 'Comemoração', '#fb7185'),
  art('fe-confetti', 'Confete', '#f472b6'),
  art('fe-fire', 'Chama', '#f97316'),
  art('fe-heart-fire', 'Coração em chamas', '#fb7185'),
  art('fe-voltage', 'Alta tensão', '#fcd34d'),
  art('fe-rocket', 'Foguete espacial', '#fb923c'),
  art('fe-comet', 'Cometa', '#818cf8'),
  art('fe-boom', 'Impacto', '#f97316'),
  art('fe-brain', 'Cérebro', '#f9a8d4'),
  art('fe-bulb', 'Lâmpada', '#fbbf24'),
  art('fe-gem', 'Joia', '#22d3ee'),
  art('fe-muscle', 'Força', '#f59e0b'),
  art('fe-mech-arm', 'Braço mecânico', '#94a3b8'),
  art('fe-wand', 'Varinha mágica', '#a78bfa'),
  art('fe-handshake', 'Aperto de mãos', '#fbbf24'),
  art('fe-raising-hands', 'Mãos ao alto', '#f59e0b'),
  art('fe-clap', 'Aplausos', '#fb923c'),
  art('fe-heart-hands', 'Mãos em coração', '#fb7185'),
  art('fe-heart', 'Coração vermelho', '#ef4444'),
  art('fe-heart-sparkle', 'Coração brilhante', '#f472b6'),
  art('fe-heart-grow', 'Coração crescente', '#fb7185'),
  art('fe-target', 'Mira', '#f87171'),
  art('fe-puzzle', 'Peça de encaixe', '#34d399'),
  art('fe-key', 'Chave dourada', '#fbbf24'),
  art('fe-old-key', 'Chave antiga', '#d97706'),
  art('fe-shield', 'Proteção', '#38bdf8'),
  art('fe-gear', 'Mecanismo', '#94a3b8'),
  art('fe-wrench', 'Chave inglesa', '#94a3b8'),
  art('fe-tools', 'Ferramentas', '#94a3b8'),
  art('fe-chart-up', 'Gráfico em alta', '#22c55e'),
  art('fe-bar-chart', 'Gráfico de barras', '#60a5fa'),
  art('fe-laptop', 'Notebook', '#60a5fa'),
  art('fe-satellite', 'Satélite', '#38bdf8'),
  art('fe-telescope', 'Telescópio', '#818cf8'),
  art('fe-microscope', 'Microscópio', '#c4b5fd'),
  art('fe-test-tube', 'Tubo de ensaio', '#34d399'),
  art('fe-compass', 'Rosa dos ventos', '#fbbf24'),
  art('fe-detective', 'Detetive', '#94a3b8'),
  art('fe-books', 'Livros', '#818cf8'),
  art('fe-grad-cap', 'Formatura', '#60a5fa'),
  art('fe-megaphone', 'Alto-falante', '#fb923c'),
  art('fe-bell', 'Sininho', '#fbbf24'),
  art('fe-seedling', 'Muda', '#34d399'),
  art('fe-tree', 'Árvore', '#22c55e'),
  art('fe-sun', 'Sol radiante', '#fbbf24'),
  art('fe-moon', 'Lua crescente', '#818cf8'),
  art('fe-rainbow', 'Arco-íris', '#f472b6'),
  art('fe-mountain', 'Montanha', '#38bdf8'),
  art('fe-eagle', 'Águia', '#a16207'),
  art('fe-owl', 'Coruja', '#a78bfa'),
  art('fe-dragon', 'Dragão', '#22c55e'),
  art('fe-unicorn', 'Unicórnio', '#f472b6'),
  art('fe-sunflower', 'Girassol', '#facc15'),

  // Teclas numéricas (keycaps) — para selos por nível (ex. tempo de casa).
  art('fe-num-1', 'Número 1', '#fb923c'),
  art('fe-num-2', 'Número 2', '#facc15'),
  art('fe-num-3', 'Número 3', '#34d399'),
  art('fe-num-4', 'Número 4', '#38bdf8'),
  art('fe-num-5', 'Número 5', '#818cf8'),
  art('fe-num-6', 'Número 6', '#a78bfa'),
  art('fe-num-7', 'Número 7', '#f472b6'),
  art('fe-num-8', 'Número 8', '#fb7185'),
  art('fe-num-9', 'Número 9', '#22d3ee'),
  art('fe-num-10', 'Número 10', '#facc15'),
]

export const DEFAULT_ART_KEY = 'trophy'

const ART_BY_KEY = new Map(BADGE_ART.map((a) => [a.key, a]))

export function badgeArt(key: string): BadgeArt | undefined {
  return ART_BY_KEY.get(key)
}

const KIND_FALLBACK_COLOR: Record<string, string> = {
  IMPACT: '#facc15',
  RECURRENCE: '#2dd4bf',
  CATEGORY: '#52fba2',
  HIGHLIGHT: '#fb923c',
}

/** Cor do medalhão: cor da arte escolhida, ou cor por kind, ou verde padrão. */
export function badgeAccentColor(iconKey: string, kind: string): string {
  return badgeArt(iconKey)?.color ?? KIND_FALLBACK_COLOR[kind] ?? '#52fba2'
}
